export const PERMISSIONS = {
  ADD_MEMBER: "ADD_MEMBER",
  REMOVE_MEMBER: "REMOVE_MEMBER",
  UPDATE_MEMBER_ROLE: "UPDATE_MEMBER_ROLE",
  CREATE_TASK: "CREATE_TASK",
  ASSIGN_TASK: "ASSIGN_TASK",
  UPDATE_TASK: "UPDATE_TASK",
  VIEW_PROJECT: "VIEW_PROJECT"
};

export const ROLE_PERMISSIONS = {
  OWNER: Object.values(PERMISSIONS),
  ADMIN: [
    PERMISSIONS.ADD_MEMBER,
    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.ASSIGN_TASK,
    PERMISSIONS.UPDATE_TASK,
    PERMISSIONS.VIEW_PROJECT
  ],
  MEMBER: [
    PERMISSIONS.UPDATE_TASK,
    PERMISSIONS.VIEW_PROJECT
  ]
};